[jammy] fix: On Gnome 42, close launcher on click outside of it
pop-os/shell pull request #1389
Opened 2022-04-01 21:17 UTC by ids1024

Fixes https://github.com/pop-os/shell/issues/1386.

This breaks the behavior on older Gnome Shell versions. If we want this branch to work there as well, it would be easy to make it conditional.

I don't know if there are any other undesired behavior changes here or the other places `shellReactive: true` is used, but it seems to basically work as expected now.

2022-04-01 21:28 UTC, mmstick approved these changes

2022-04-04 16:39 UTC, n3m0-22 approved these changes
Tested and working correctly on GNOME 40.5. I see no other undesired behaviors.

2022-04-04 16:43 UTC, leviport requested changes
Need to test on 22.04 (which should have Gnome 42)

2022-04-04 18:27 UTC, n3m0-22 approved these changes
Working properly in 22.04 GNOME 42

2022-04-04 19:06 UTC, merged