feature: maintain maximized windows
pop-os/shell pull request #1461
Opened 2022-06-02 17:44 UTC by pkoutsovasilis

This PR provides a "solution" to [this issue](https://github.com/pop-os/shell/issues/1458). Specifically, it introduces a new option, in the extension settings, which when enabled maximized windows are maintained on focus change events.

For my workflow this feature is really useful. If you find it useful as well, I am more than happy to perform any requested changes.

Cheers

2022-06-02 18:12 UTC, mmstick commented
Wouldn't this be fixed by avoiding the unmaximize on focus of a floating window? That is the intended fix for this.

2022-06-02 18:23 UTC, pkoutsovasilis commented
@mmstick what you mention indeed covers the case of floating windows, but what if I don't have a floating window and just need a normal window for some reason maximized (I think this is captured by [this comment](https://github.com/pop-os/shell/issues/1458#issuecomment-1142055938)). This PR maintains maximized any window type, but as soon as you alt-tab to a windows "underneath" or open a new window on the same monitor/workspace, everything goes back to normal which makes a lot of sense to me (kinda like maximize => zoom-in with tiling => auto zoom-out feature). Again I totally get that this behavior maybe is not aligned with what the pop-os shell is trying to achieve/offer.

2022-06-02 20:12 UTC, mmstick submitted a review, later dismissed
I'd still like to reach a better default behavior though

2022-06-02 20:14 UTC, pkoutsovasilis commented
@mmstick by default this behavior I describe above is disabled, so no changes in the default/average user experience. That said, I am more than happy to help if I can with what you think it would be more appropriate

2022-06-02 20:16 UTC, jacobgkau commented
> what if I don't have a floating window and just need a normal window for some reason maximized (I think this is captured by [this comment](https://github.com/pop-os/shell/issues/1458#issuecomment-1142055938)).

That comment is about wanting maximization retained on workspace switch, which is also something that might make sense as default behavior.

> This PR maintains maximized any window type, but as soon as you alt-tab to a windows "underneath" or open a new window on the same monitor/workspace, everything goes back to normal

This sounds like the intended behavior of maximization. Besides handling floating window focus and workspace switch, what else normally doesn't work that this would solve? (I haven't tried this yet, but it's building on our build server for testing.)

2022-06-02 20:19 UTC, jacobgkau commented
Okay, testing this now, it does look like the new setting is fixing maximization behavior, particularly for workspace switching. I'm not opposed to having options for changing how maximization is handled, but it seems like this fix could simply be applied to the default behavior without adding any options in this case, unless I'm missing something else so far.

2022-06-02 20:20 UTC, mmstick commented
If this seems like a better default then we can make it so.

2022-06-02 20:24 UTC, pkoutsovasilis commented
@jacobgkau I am gonna be honest and say that it did not cross my mind that this was the intended behavior of maximized windows... And in my effort not to step on anybodys toes I made this behavior tunable :smile: Mainly it addresses the two comments highlighted by the aforementioned issue, with an extra twist that when you alt-tab (or switch via launcher) in an "underneath" window or open a new windows on the same monitor and workspace the windows is given back to auto-tiling and all this magic happens.. I can provide some visual feedback if necessary

2022-06-02 20:29 UTC, mmstick commented
We can remove the option and make it the default behavior.

2022-06-02 20:37 UTC, jacobgkau commented
The intent of unmaximizing on focus change is to not have tiled windows "floating" over a maximized window (with an unseen gap in the tree) and more generally to not have a maximized window break keyboard navigation. Changing workspaces shouldn't move or resize anything-- a user expects a workspace to look the same when coming back to it as it looked before switching away.

> Mainly it addresses the two comments highlighted by the aforementioned issue, with an extra twist that when you alt-tab (or switch via launcher) in an "underneath" window or open a new window on the same monitor and workspace the window is given back to auto-tiling and all this magic happens.

Alt-tab on the same workspace already unmaximized a window and I'm seeing it continue to do so now (whether the new setting is enabled or disabled.) Alt-tab between workspaces used to unmaximize and no longer does with the setting enabled, which is expected as described above.

Focusing a window with the launcher used to leave the maximized window maximized, and still does, whether the setting is enabled or disabled. I think I would expect this to unmaximize the window (to be consistent with alt-tab and clicking windows.)

2022-06-02 20:43 UTC, pkoutsovasilis commented
> Focusing a window with the launcher used to leave the maximized window maximized, and still does, whether the setting is enabled or disabled. I think I would expect this to unmaximize the window (to be consistent with alt-tab and clicking windows in the Workspaces menu.)

@jacobgkau thanks for the feedback! definitely I missed something, I will have a look and push the commit :smile:

2022-06-02 21:33 UTC, pkoutsovasilis commented
@jacobgkau switching to a window from launcher now unmaximizes any window on the same monitor and workspace

2022-06-03 00:01 UTC, pkoutsovasilis commented
@mmstick @jacobgkau in order to support treating as ```floating``` the window of the intellij search dialog (I assume this applies to other jetbrains products as well) I extended the floating rules and introduced the field of ```window_type```. Initially, I tried to nail this down only by the existing criteria of ```wm_class``` and the ```wm_title``` but unfortunately when the main window of intellij starts it has the same wm_class and wm_title as the search dialog. So, now I am

2022-06-03 00:09 UTC, mmstick commented
The dialog window type should be floating regardless of exceptions. Is this a case where the window type is changing after the window is opened? Because only normal window types are permitted to tile.

2022-06-03 00:15 UTC, pkoutsovasilis commented
Ok so this is as I suspected then, dialog window type should be floating. To this end, shouldn't the ```window_shall_float(...)``` check if the window type is a dialog and return true? because now it does not. In the case of intellij, the sequence is the following, spashscreen (normal type) -> welcome to Intellij or already opened project (normal type) -> [ctrl+shift+f] brings up a new global search window (dialog type).

2022-06-03 00:17 UTC, mmstick commented
That is checked here: https://github.com/pop-os/shell/blob/master_jammy/src/window.ts#L312

2022-06-03 00:27 UTC, pkoutsovasilis commented
thanks for that pointer @mmstick, I definitely missed this out. Now this simplifies my approach by a lot! You see the ```is_floating``` caught my eye and tried to achieve this from that way :smile: but I was wrong. With your help, now focused floating windows wont unmaximize a previously maximized window

2022-06-03 11:43 UTC, mmstick requested changes

2022-06-03 11:43 UTC, mmstick commented on schemas/org.gnome.shell.extensions.pop-shell.gschema.xml
> +        </key>
Needs to be removed

2022-06-03 11:43 UTC, mmstick commented on src/extension.ts
> +                            }
Same here

2022-06-03 11:43 UTC, mmstick commented on src/extension.ts
> +                    break;
Here

2022-06-03 11:43 UTC, mmstick commented on src/extension.ts
> +        }
Here

2022-06-03 11:43 UTC, mmstick commented on src/extension.ts
> +
Here

2022-06-03 11:43 UTC, mmstick commented on src/extension.ts
> +                }
These

2022-06-03 11:43 UTC, mmstick commented on src/prefs.ts
> +    });
This

2022-06-03 11:43 UTC, mmstick commented on src/extension.ts
> +                        }
This

2022-06-03 11:43 UTC, mmstick commented on src/prefs.ts
> +    maintain_maximized_windows: any,
This

2022-06-03 11:43 UTC, mmstick commented on src/prefs.ts
> +    });
This

2022-06-03 11:43 UTC, mmstick commented on src/settings.ts
> +const MAINTAIN_MAXIMIZED_WIDOWS = "maintain-maximized-windows";
These

2022-06-03 11:43 UTC, mmstick commented on src/tags.ts
> +export var MaintainMaximized = 4;
This

2022-06-03 12:05 UTC, pkoutsovasilis commented
@mmstick I saw the requested changes and I guess that we are going to make this the default behavior. But if we do so, we are actually making ```unmaximize_workspace(null)``` obsolete. If that's the case, should I remove the aforementioned calls to ```unmaximize_workspace``` with null?

2022-06-03 12:50 UTC, mmstick commented
Sure

2022-06-03 13:47 UTC, pkoutsovasilis commented
@mmstick this now alters the default behavior of maximized windows as described in the comments above

2022-06-03 14:23 UTC, mmstick approved these changes

2022-06-06 20:40 UTC, jacobgkau approved these changes
Fixes both issues described in https://github.com/pop-os/shell/issues/1458 (IntelliJ no longer unmaximizes when opening the search dialogue with double-pressing Shift, and switching workspaces no longer causes a maximized window to unmaximize.)

Regression testing passed: [shell-pr1461-jammy.txt](https://github.com/pop-os/shell/files/8847798/shell-pr1461-jammy.txt)

2022-06-07 07:46 UTC, frezbo commented
this should also fix this https://github.com/pop-os/shell/issues/1440#issuecomment-1145700475= :+1:

2022-06-07 09:50 UTC, merged