fix: update workareas only after screen unlock
pop-os/shell pull request #1469
Opened 2022-06-07 22:45 UTC by pkoutsovasilis

This PR offers a solution to [this issue](https://github.com/pop-os/shell/issues/1467).

2022-06-08 14:55 UTC, mmstick approved these changes

2022-06-08 16:04 UTC, jacobgkau requested changes
This fixes https://github.com/pop-os/shell/issues/1467, but after the change, if I open up windows and then restart GNOME Shell with Alt-F2, r, Enter, then the tree goes behind the top bar and dock:

![Screenshot from 2022-06-08 10-00-47](https://user-images.githubusercontent.com/7199422/172663901-feb73054-95fd-4701-a6eb-1c6035aa34ee.png)

Restarting GNOME Shell is somewhat common in both testing and troubleshooting, so that seems like an issue. If I close _all_ windows and then open some windows back up, that doesn't happen anymore; but then if I e.g. move the dock, then the tree doesn't update to get out of the way of that either.

![Screenshot from 2022-06-08 10-03-28](https://user-images.githubusercontent.com/7199422/172664196-72b166b4-dfc1-4e75-92c4-d5a51d9d352c.png)

2022-06-08 16:10 UTC, pkoutsovasilis commented
good catch @jacobgkau I admit that I didn't occur to me to test this on gnome reset. I suspect that on gnome reset the param ```workareas_only``` is "erroneously" set to ```true``` where it should be ```false```... I will come back on this

2024-08-23 07:49 UTC, pkoutsovasilis commented
this is no longer relevant 🙂

2024-08-23 07:49 UTC, closed without merging