Add firefox exception except main window
pop-os/shell pull request #1494
Opened 2022-07-06 22:29 UTC by p1gp1g

It is convenient to have non-main window in floating mode.

It fixes #756 and maybe other issues.

2022-07-07 17:36 UTC, n3m0-22 requested changes
I'm seeing the new floating window exception, but it makes no change in the behavior of Firefox's sharing indicator. With the new exception enabled or disabled the sharing indicator is pinned to the top bar. It can be moved to anywhere on the top bar, but not away from it. As far as I can tell this is not doing anything. Is it your intention that this would allow the sharing indicator to be moved anywhere on the screen?

Examples: 
![Screenshot from 2022-07-07 11-27-11](https://user-images.githubusercontent.com/11048214/177835290-10ac75eb-4955-49b8-8246-673245370a97.png)
![Screenshot from 2022-07-07 11-27-36](https://user-images.githubusercontent.com/11048214/177835312-a5cee1bb-443a-4d83-b1f2-40b80f7acdbc.png)

2022-07-07 17:50 UTC, n3m0-22 commented
I think this same issue was mentioned [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1705048), and seems to have been [fixed](https://hg.mozilla.org/integration/autoland/rev/1f8208b4e636) with the way Wayland handles Firefox popup windows. This may no longer be necessary.

2022-07-08 08:03 UTC, p1gp1g commented
I guess I should have given more context first.

I'm using : 
* Manjaro with Gnome
* pop os shell extension
* Latest firefox on wayland
  * The sharing indicator can go wherever if it is *not* in tilling mode

This PR was not about the the sharing indicator in particular, many non-main windows should be in floating mode for convenience.

For instance:
* Picture-in-Picture
* Page information
* Sharing indicator
* Bookmarks
* etc.

Here are 2 screenshots before and after the exception to illustrate

**Before**
![Capture d’écran du 2022-07-08 09-34-10](https://user-images.githubusercontent.com/31284753/177946054-4b18cbcf-0c49-4f16-8ef6-2178ff518893.png)

**After**
![Capture d’écran du 2022-07-08 09-52-25](https://user-images.githubusercontent.com/31284753/177946078-27b035b3-247d-4f67-9ae2-c71ef0f5bf14.png)

Because of the lake of context and the resulting misunderstanding, another review is then welcome @n3m0-22 :)

2022-07-08 15:12 UTC, n3m0-22 submitted a review, later dismissed
This looks good. I've tested it on Pop and Manjaro. It works as described. Thank you for the more detailed explanation as well as your contribution.

2022-07-08 16:50 UTC, n3m0-22 approved these changes
All testing passed. This is good to go.
[shell-testing.txt](https://github.com/pop-os/shell/files/9073820/shell-testing.txt)

2022-07-08 17:04 UTC, mmstick approved these changes

2022-07-08 17:19 UTC, merged