feat: active-hint-border-radius
pop-os/shell pull request #1509
Opened 2022-08-18 11:50 UTC by bennypowers

Adds an `active-hint-border-radius` configuration setting to the database and to the panel UI

![Screenshot from 2022-08-18 14-47-08](https://user-images.githubusercontent.com/1466420/185387537-ca181eff-a1f7-405c-9459-4bdb8d076fce.png)

Reviewers, please take a look at the settings schema and code, as I was not yet able to view the setting with description in dconf-editor

![Screenshot from 2022-08-18 14-49-44](https://user-images.githubusercontent.com/1466420/185387770-327c39b9-ddbd-4bad-a22d-553714eb747c.png)

2022-08-18 18:06 UTC, n3m0-22 approved these changes
Tested on Pop and Fedora all testing passed

[shell-testing.txt](https://github.com/pop-os/shell/files/9376339/shell-testing.txt)

The `no schema found` issue is due to it being installed at user level vs system. @bennypowers If you would like it to show in `dconf-editor` the following will fix it for your local install.

`sudo cp schemas/org.gnome.shell.extensions.pop-shell.gschema.xml /usr/share/glib-2.0/schemas/`
`sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`

You may need to logout, reboot, or restart GNOME to see the change.

Example in Fedora:

![Screenshot from 2022-08-18 11-53-41](https://user-images.githubusercontent.com/11048214/185463828-94f4801d-cd2b-4275-ad99-14c432ffc08c.png)

2022-08-18 21:10 UTC, bennypowers commented
Amazing, I'll give that a try, and thanks for the review.

I noticed that window content can overflow the border. That may be an issue for a subsequent MR though. See e.g. the corners if the wezterm instance in the above screenshot.

2022-08-18 21:19 UTC, n3m0-22 requested changes
That could be an issue. I will need to look into that further.

2022-08-18 22:40 UTC, n3m0-22 commented
@bennypowers I don't think it is too much of an issue as it doesn't have much impact on window contents unless the radius is set to greater that 30 and/or the window is very small. It seems there is a sweet spot between around 12 - 15 that works well for vanilla gnome. Would you be able to add an upper limit of 15? No lower limit is needed, and the default of 5 is good as it keeps the look consistent for Pop!_OS.

2022-08-19 08:37 UTC, bennypowers commented
Initially I tried implementing a [QuickSlider](https://github.com/GNOME/gnome-shell/blob/b7d738dfffab07f84649b647ea9ce639f37079a4/js/ui/quickSettings.js#L149), but that fight was, alas, beyond my experience/interest. So instead I added some optional params to `clamp` and an override to `number_entry`

2022-08-19 16:34 UTC, n3m0-22 approved these changes
I think this is a good compromise. It allows for enough variation to account for user preference. I suppose a user can still overdo it with the radius, but it is very easy to revert to a more acceptable setting.

Tested again on Pop and Fedora. Testing is still passing. This looks good to me.

Thank you for contributing to Pop!_OS.

2022-09-01 11:17 UTC, mmstick approved these changes

2022-09-01 11:18 UTC, merged