fix: Avoid calling system76-scheduler if it fails
pop-os/shell pull request #1515
Opened 2022-09-02 13:48 UTC by mmstick

Closes #1513

2022-09-02 19:20 UTC, jacobgkau requested changes
Replicated the logs from https://github.com/pop-os/shell/issues/1513 after removing system76-scheduler.

This fix does not seem to work; I still get dbus errors every time I switch focus without system76-scheduler installed.

![Screenshot from 2022-09-02 13-18-48](https://user-images.githubusercontent.com/7199422/188222843-4c6867f3-5ff8-455f-9818-865b62e5b7a1.png)

2022-09-02 21:04 UTC, mmstick commented
Didn't work because the function is async. It should be working now that the async responses are handled.

2022-09-06 06:16 UTC, jacobgkau approved these changes
This is working now. When system76-scheduler is not installed, I get one log line of:

```
Sep 06 00:00:30 pop-os gnome-shell[3823]: pop-shell:  [WARN] system76-scheduler may not be installed and running: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

...and then no lines when I switch focus between apps. With system76-scheduler installed, focus still changes the priority as expected.

2022-09-06 20:22 UTC, 13r0ck approved these changes

2022-09-06 20:38 UTC, merged