active border radius minimum zero
pop-os/shell pull request #1523
Opened 2022-09-27 15:55 UTC by n3m0-22

This changes the lower bound for the Active Border Radius to zero per user request https://github.com/pop-os/shell/issues/1522. This does not change the default value.

2022-09-27 16:57 UTC, 13r0ck submitted a review, later dismissed

2022-09-28 22:18 UTC, jacobgkau requested changes
This allows me to change the option in the top-right menu below 5 (down to 0), but values below 5 do not take effect or propagate to the gsettings entry. Trying to set the value to below 5 via `gsettings set` also doesn't work. I think there's a remaining limit elsewhere in the code.

![Screenshot from 2022-09-28 14-58-55](https://user-images.githubusercontent.com/7199422/192898742-38c48088-8712-495c-a463-213c6600ee97.png)

2022-09-29 15:18 UTC, jacobgkau approved these changes
This is working now:
![Screenshot from 2022-09-29 09-17-06](https://user-images.githubusercontent.com/7199422/193071240-4721c038-66be-4636-98ed-e62926ff6c63.png)
Does not affect the default.

2022-09-29 15:35 UTC, mmstick approved these changes

2022-09-29 15:36 UTC, merged