fix: don't raise stacked windows on focus
pop-os/shell pull request #1540
Opened 2022-11-02 04:28 UTC by mooey5775

Fixes #1539. Stacked windows no longer raise when focused, but still raise when activated normally.

Am new to contributing to Pop Shell - let me know if there is some testing needed for this PR.

2022-11-02 17:52 UTC, n3m0-22 requested changes
I am seeing no difference in the focus behavior of stacks. Tested on both Fedora 36 and Pop!_OS 22.04. 

@mooey5775 are you seeing this working on your system? Following the steps listed in https://github.com/pop-os/shell/issues/1539 the focus action remains the same.

2022-11-03 04:24 UTC, mooey5775 commented
It does work for me - I've recorded some videos of the difference in behavior tested on a clean Fedora 36 VM. I've tried installing Pop!_OS but GNOME Boxes is hanging on install.

Pre-patch:
[886a069.webm](https://user-images.githubusercontent.com/7400724/199647320-1c69ff26-27cc-407f-a692-eb09ea55203d.webm)

Post-patch:
[1f349fc.webm](https://user-images.githubusercontent.com/7400724/199647328-063e34a0-9060-4794-8f35-fa7264587872.webm)

2022-11-03 13:32 UTC, n3m0-22 approved these changes
It does seem to be working now. It is working with no regressions on Pop. I'm not sure what the issue was before, but I have it working like your examples on a couple different installs of Fedora. All shell testing passed.

[shell-testing.txt](https://github.com/pop-os/shell/files/9929596/shell-testing.txt)

2022-11-03 13:33 UTC, mmstick approved these changes

2022-11-03 13:34 UTC, merged

2022-11-03 13:34 UTC, mmstick commented
Thanks!