fix: gnome 47 and meta 15 support
pop-os/shell pull request #1734
Opened 2024-10-01 18:40 UTC by CodeAndGin

Fix for #1732, updating window.is_client_decorated() to window.decorated

2024-10-01 20:14 UTC, jackpot51 submitted a review, later dismissed

2024-10-03 23:33 UTC, jacobgkau requested changes
Thank you for the update!

Testing on Fedora 40 with GNOME 46, this breaks the `Show Window Titles` toggle, which is available under Xorg. As you can see in the below screenshot, LibreOffice still has its title even when the option's turned off, and the terminal (with CSD) appears inside of an extra frame (this happens if the window's open before I switch the option off).

![Screenshot from 2024-10-03 17-21-10](https://github.com/user-attachments/assets/d0d47a5c-896d-4eec-89ee-2e1f3b589968)

Neither of these things happen with the current `master_noble` branch, as you can see below. (If I recreate the above issue on the new version, then install the old version and restart GNOME Shell, the terminal still has the frame until I close it and re-open it, but I can't replicate it from scratch on the old version.)

![Screenshot from 2024-10-03 17-23-16](https://github.com/user-attachments/assets/966f0611-3fc2-4e83-95c0-38bf49a69449)

If possible, can you gate this behavior change behind a check of the GNOME Shell version? You can see an example of doing that here: https://github.com/pop-os/shell/blob/ced54427487905f42447a07dabff7101b700b5c9/src/extension.ts#L2036 

If that's not possible, then we'll need to create another branch for GNOME 47+. Our branches are integrated with our CI, which usually tracks Ubuntu releases; it does look like Oracular (24.10) has GNOME 47, so we could make a `master_oracular` if necessary (although I don't think our CI is set up for it yet).

2024-10-04 01:27 UTC, CodeAndGin commented
Been looking at this in a bit more depth. Found a version of an older Meta api. window.is_client_decorated() and window.decorated are not, as I naively assumed, cognate. is_client_decorated() is checking if the decorations are being handled by the window, and it's used to continue the for loop because otherwise the weird frame thing happens.

is_client_decorated() was removed from the API, which is _annoying_ because stuff like this is outside of my expertise and I don't know how to hack together something that can check for what is_client_decorated() was checking for.

Basically, whoops this wasn't a fix at all because I missed the _why_ and a simple version check won't solve the issue except on 46 and earlier.

2024-10-04 13:01 UTC, CodeAndGin commented
I've just pushed a new commit; I _think_ the new function I wrote is doing the same hacky thing that the API version of is_client_decorated() was doing, based on the comments in the old code that defined it. I am _not_ particularly versed in how xprop properties work though, so I'm kinda running blind here. _However_ what I've written _seems_ to do the expected behaviour correctly on my system. If it still needs a version gate let me know.

2024-10-04 17:17 UTC, jacobgkau approved these changes
On 209ab01, there no longer seems to be any regression on GNOME 46. The window titles option works normally under Xorg. That option is not available on Wayland, but tiling is still working as expected on Wayland.

2024-10-09 08:42 UTC, McCio approved these changes
LGTM

2024-10-09 12:08 UTC, mmstick approved these changes

2024-10-09 12:09 UTC, merged