Dev Rollup
pop-os/shell pull request #975
Opened 2021-05-21 22:27 UTC by mmstick

Promising results with handling display hotplugging and replugging.

2021-05-24 16:54 UTC, bflanagin commented
#973 fix confirmed based on user supplied steps. 
#964 resolved and working.

2021-05-24 18:18 UTC, bflanagin commented
#794 Not fixed

![Screenshot from 2021-05-24 11-50-26](https://user-images.githubusercontent.com/10382037/119381996-155dae80-bc87-11eb-9440-45933e1dc98c.png)

Before locking the screen I have two windows on both the primary and secondary screen. They are both on workspace 2.

![Screenshot from 2021-05-24 11-51-26](https://user-images.githubusercontent.com/10382037/119382179-4f2eb500-bc87-11eb-8dd1-ad3ac46a5c7e.png)

After manually locking the screen, waiting  ~2 minutes, and returning from lock the windows have all shifted to the other display. Whats interesting is that the windows that were on workspace 2 on the primary display (set as my external monitor) are now on workspace 3 and the other two windows remain on workspace 2. 

It's very inconsistent, After triggering the bug for the forth time in a row it has suddenly stopped. The only thing I did between the 4th and 5ith attempt was opening the Displays panel in Gnome Control Center.

2021-05-24 18:23 UTC, bflanagin commented
#957 fixed but with caveats. 

I'm not seeing the issue described int #957 the where the windows move workspaces on unlock. If they don't move as mentioned in above they stay on their respective work space.

2021-05-26 20:11 UTC, jacobgkau commented
When I started in this configuration and changed the primary display from the smaller one (internal) to the larger one (external):

![Screenshot from 2021-05-26 14-06-28](https://user-images.githubusercontent.com/7199422/119724308-cb61fd80-be2b-11eb-999f-eedb7b782802.png)

The windows on the external display moved to a new workspace, and one of them moved to the internal display:

![Screenshot from 2021-05-26 14-07-32](https://user-images.githubusercontent.com/7199422/119724334-d2890b80-be2b-11eb-8352-114b640aa5ab.png)

This is a regression. It happened twice in a row, then stopped, but happened again after I restarted GNOME Shell.

2021-06-03 13:44 UTC, jackpot51 commented
What does the dedicated GPU selection look like?

2021-06-03 14:57 UTC, jacobgkau commented
> What does the dedicated GPU selection look like?

It looks like this:
![graphics](https://user-images.githubusercontent.com/7199422/120666223-a849d600-c449-11eb-92d3-cf04f82e1485.png)

2021-06-03 14:58 UTC, jacobgkau requested changes
Clicking outside of the launcher to close it does not clear the launcher text, and upon re-opening the launcher, no search results show up until at least one character is added/removed. Seems like the text should be cleared when exiting by click the same as exiting by keyboard, or else the search results need to show up immediately when re-opening.

2021-06-07 21:34 UTC, jacobgkau approved these changes
#794 - Not able to recreate (looks like was already fixed?)
#831 - Fixed.
#880 - Not fixed.
#934 - Fixed.
#948 - Fixed.
https://github.com/pop-os/shell/issues/957 - Doesn't seem fixed, but not sure if what I saw was the same issue (windows on internal display moved down a workspace after locking/unlocking, while windows on external display stayed put.)
#960 - Not fixed (this is a duplicate of #880.)
#964 - Fixed.
#973 - Fixed.
#976 - Fixed.
#978 - Fixed.
#979 - Fixed.
#980 - Fixed.

Regression testing passed. (20.10 and 21.04 had a couple of issues, but I recreated them on the `master` branch.)
[shell-pr975-run2-focal.txt](https://github.com/pop-os/shell/files/6612075/shell-pr975-run2-focal.txt)
[shell-pr975-run2-groovy.txt](https://github.com/pop-os/shell/files/6612031/shell-pr975-run2-groovy.txt)
[shell-pr975-run2-hirsute.txt](https://github.com/pop-os/shell/files/6611650/shell-pr975-run2-hirsute.txt)

2021-06-07 21:35 UTC, mmstick commented
Moving unfixed issues for the next PR

2021-06-07 21:38 UTC, merged